---
- name: Backup Databases
  hosts: db_servers
  become: yes
  vars:
    backup_dir: /backups
    db_name: myapp_db
    db_user: myapp_user
    db_password: SuperSecurePassword123

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup PostgreSQL database
      command: >
        PGPASSWORD={{ db_password }} pg_dump -U {{ db_user }} {{ db_name }} > {{ backup_dir }}/{{ db_name }}_{{ ansible_date_time.iso8601 }}.sql
      args:
        creates: "{{ backup_dir }}/{{ db_name }}_{{ ansible_date_time.iso8601 }}.sql"

