---
- name: Provision Web Servers
  hosts: web_servers
  become: yes
  vars:
    apache_port: 80

  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Install Apache and necessary packages
      apt:
        name:
          - apache2
          - libapache2-mod-wsgi-py3
          - python3-pip
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy website files
      copy:
        src: ./www/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Configure Apache to listen on custom port
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: "Listen {{ apache_port }}"
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

