---
- name: Deploy Docker Application
  hosts: docker_hosts
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: myrepo/myapp
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: myapp_container
        image: myrepo/myapp:latest
        state: started
        ports:
          - "8080:80"

