---
- name: Setup Monitoring with Prometheus and Grafana
  hosts: monitoring_servers
  become: yes

  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start Grafana service
      service:
        name: grafana
        state: started
        enabled: yes

    - name: Configure Grafana datasource
      grafana_datasource:
        name: Prometheus
        type: prometheus
        url: http://localhost:9090
        access: proxy
        is_default: true
        state: present

