---
- name: Set Up PostgreSQL Database
  hosts: db_servers
  become: yes
  vars:
    db_name: myapp_db
    db_user: myapp_user
    db_password: SuperSecurePassword123

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database
      postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "ALL"
        db: "{{ db_name }}"
        state: present

